[project]
name = "student-reg-ap-project"
version = "0.1.0"
description = "student reg django project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "django>=5.2.6",
    "django-browser-reload>=1.18.0",
    "django-tailwind>=4.2.0",
]
