# Generated by Django 5.2.6 on 2025-09-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField()),
                ('slots', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField()),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='MajorUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Speciality Units'), (2, 'Primary Units'), (3, 'Optional Units'), (4, 'General Units')])),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.major')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('price', models.PositiveIntegerField()),
                ('paid', models.BooleanField()),
                ('passed', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('time', models.ManyToManyField(to='courses.timeslots')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, verbose_name=255)),
                ('unit_size', models.PositiveSmallIntegerField()),
                ('majors', models.ManyToManyField(related_name='units', through='courses.MajorUnit', to='users.major')),
            ],
        ),
        migrations.AddField(
            model_name='majorunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.unit'),
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.unit'),
        ),
    ]
