# Generated by Django 5.2.6 on 2025-09-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='coursestudentstatus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursestudentstatus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='majorunit',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.major'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='time_slot',
            field=models.ManyToManyField(to='courses.timeslots'),
        ),
        migrations.AddField(
            model_name='unit',
            name='majors',
            field=models.ManyToManyField(related_name='units', through='courses.MajorUnit', to='users.major'),
        ),
        migrations.AddField(
            model_name='majorunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.unit'),
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.unit'),
        ),
    ]
