# Generated by Django 5.2.6 on 2025-09-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_semester_remove_course_active_remove_course_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudentstatus',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='time_slot',
            field=models.ManyToManyField(to='courses.timeslots'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
