# Generated by Django 5.2.6 on 2025-09-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='code_name',
            new_name='codename',
        ),
        migrations.AlterField(
            model_name='coursestudentstatus',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursestudentstatus',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
