# Generated by Django 5.2.6 on 2025-09-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_code_name_semester_codename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorunit',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Speciality Units'), (2, 'Primary Units'), (3, 'Optional Units'), (4, 'General Units')], null=True),
        ),
    ]
