# Generated by Django 5.2.6 on 2025-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_majorunit_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='is_prerequisite_for', to='courses.unit'),
        ),
    ]
