# Generated by Django 5.2.6 on 2025-09-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_unit_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudentstatus',
            name='paid',
            field=models.BooleanField(blank=True),
        ),
    ]
