# Generated by Django 5.2.4 on 2025-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_unit_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudentstatus',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت\u200cنام'),
        ),
    ]
