# Generated by Django 5.2.6 on 2025-09-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_coursestudentstatus_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, help_text='Upload a file (PDF, DOC, etc.)', null=True, upload_to='course_attachments/%Y/%m/%d/')),
                ('text_content', models.TextField(blank=True, help_text='Enter text content directly (e.g., announcements, instructions)', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text="Optional description of the attachment's content.")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course Attachment',
                'verbose_name_plural': 'Course Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
