# Generated by Django 5.2.6 on 2025-09-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursestudentstatus_registered_at'),
        ('courses', '0007_courseattachment'),
    ]

    operations = [
    ]
